apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.appName}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
      - name: {{.Values.appName}}
        image: {{.Values.flaskImage}}
        imagePullPolicy: {{.Values.pullPolicy}}
        ports:
        - containerPort: {{.Values.flaskDeploymentPort}}
        volumeMounts:
        - name: {{.Values.pvcName}}
          mountPath: {{.Values.pvcPath}}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      volumes:
      - name: {{.Values.pvcName}}
        persistentVolumeClaim:
          claimName: {{.Values.pvcName}}