apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
  namespace: {{.Values.appName}}
spec:
  selector:
    app: {{.Values.appName}}
  ports:
  - port: {{.Values.flaskDeploymentPort}}
    targetPort: {{.Values.flaskDeploymentPort}}
  type: ClusterIP